version: '3.7'
services:
  app:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    env_file: .env
  db:
    image: postgres:latest
    env_file: .env